version: "3.7"
services:
  test: &FULL
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 -m pytest /src/tests
    volumes:
      - .:/src
    environment:
      - GST_PLUGIN_PATH=/usr/local/lib/x86_64-linux-gnu/gstreamer-1.0
      - CODECOV_TOKEN